version: 2
updates:
  - package-ecosystem: maven
    directory: /covid19_case_tracker
    schedule:
      interval: weekly
    groups:
      spring-boot:
        patterns:
          - "org.springframework.boot*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /covid19_case_tracker
    schedule:
      interval: monthly
